apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: myapp-redis-secret
  namespace: myapp
spec:
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis/secret
        property: password